### ISSUE TITLE
Outcom RPC 175

### ISSUE THREAD

**Issue by Dayrion** [BrunoBM16/samp-packet-list#2]
RPC 175 isn't working. Unfortunaly nothing changes.
https://github.com/BrunoBM16/RPC-List/wiki/RPC-List#setactorfacingangle---id-175

**Comment by AGraber** [comment]
Can you show us the code you're using to send the RPC?

**Comment by AGraber** [comment]
SA-MP 0.3.8s announcement post (http://forum.sa-mp.com/showthread.php?t=644105) confirms that there's a bug in 0.3.7 that prevents actors from rotating properly:

```
Other fixes since 0.3.7
- The radar outline should now scale properly in widescreen resolutions.
- A bug introduced to PlayerPlaySound with sound ID 0 should be fixed.
- Actors should now be able to rotate again.
```

Can you test your code in 0.3.DL to see if it works there?

**Comment by Dayrion** [comment]
Seems to doesn't work too.

**Comment by Dayrion** [comment]
- Create a static actor, get his ID.
- Run this code
``` pawn
CMD:test_angle(playerid, params[])
{
	extract params -> new actorid; else return 1;
	new BitStream:bit_stream = BS_New();
	BS_WriteValue(bit_stream, 
		PR_UINT16, actorid,
		PR_FLOAT, 90.0);
	BS_RPC(bit_stream, playerid, 175);
	BS_Delete(bit_stream);
	return 1;
}
```
- Actor's facing angle won't change, it seems to apply an animation or something like that.

**Comment by Dayrion** [comment]
Seems this bug is deeper than that or no RPC is reserved to facing actor's facing angle. I think SAMP (`streamer` does the same thing and now, me) just hide and recreate the actor with new actor's facing angle by through RPCs onlys.

**Comment by BrunoBM16** [comment]
This issue should have been dealt with very long ago. Anyway, to the point:

In the case of the native function, it does work to set the angle for streamed players, yes, but the actor's new angle is not stored internally in the actor pool for said actor, which is why you see it in the previous angle when it gets streamed-in with you again. Shorthly, a SA-MP issue.

In the case of sending only the RPC, it is not any different. You are simply updating the actor's angle on the player's client, it is not being set in the actor pool. That being said, it is expected for the actor to be in the original position if you get streamed-in with it again. The same applies to vehicles or objects.

You may store the angle and set it again when the actor streams in, or just do what you are doing already: create it again.
