### ISSUE TITLE
"Connected" packet(s) after "Connection request" (32 bytes) packet

### ISSUE THREAD

**Issue by AdrianBZG** [BrunoBM16/samp-packet-list#29]
Hi,

I'm trying to find out how the cookie system works. I know that when a user is connecting, a 32 bytes packet is sent to request connection. My question is, what is response packet from the server after that?

Thanks.

**Comment by bldd14** [comment]
Here are the steps:
1) The client sends the ID_OPEN_CONNECTION_REQUEST (24) packet with 2 empty bytes for alignment to the server.

2) The server replies with ID_OPEN_CONNECTION_COOKIE (26) packet + the random cookie value which has a length of 2 bytes (its value is updated every (connseedtime) milliseconds, this interval can be specified in the server.cfg).

3) The client sends ID_OPEN_CONNECTION_COOKIE (26) packet + the random cookie value the server sent but xored by 0x6969 (For SA-MP 0.3.7 R1 to R4, not sure if it's the same for SA-MP 0.3DL).

4) After the server has received the response from the client, it xors the 2-byte length value the client sent with the ID_OPEN_CONNECTION_COOKIE (26) packet by 0x6969, if it's equal to the current server conncookie value (the 2 bytes random value I mentioned before) then it lets you join in, if it isn't, the process is repeated.

Keep in mind that every packet is encrypted by RakNet, that's the reason why the first packet, which only contains 3 bytes, ends as a 4 bytes value (which in addition to the 28 bytes of the header (iphdr + udphdr) gives you that 32 bytes packet).

**Comment by AdrianBZG** [comment]
@bldd14 Thanks for the detailed information.

So I question I have is, my server is under a UDP flood of the first packet (connection request) with spoofed source IP addresses. Is it possible to put an application before the server (proxy) that catches the connection requests packets and answers with the open connection cookie packet to the client, thus removing that burden from the main SA-MP thread?

Or do you have any suggestions for that?

Many thanks.

**Comment by AdrianBZG** [comment]
Hi @bldd14 ,

So I'm trying to reproduce step 3, where the user received the cookie value and has to respond with it but XORed by 0x6969.

In step 2 I get 1af1ab as a response packet (3 bytes payload), if I XOR that by 0x6969 I get 1a98c2, but that's not real real value I see in Wireshark if I connect to the server, the response is actually 021e18e8, and then the server answers with 1900, which I guess means connection accepted.

Could you please let me know where I'm getting it wrong?

**Comment by ADRFranklin** [comment]
Unfortunately there is nothing you can do at this stage to prevent udp flood, the only option you would have, because be either whitelisting IP addresses, or setting up a load balancer and distributing the connections between multiple servers, however such a thing is extremely difficult to implement with something like sa-mp, because it was never designed to be used in such a way.

I mean you could potentially put a proxy in between it and drop bad packets that sent invalid response values, but this will only work so much, and you'd had to implement the proxy yourself in it's entirety. I actually started working on this exact idea a while ago, but didn't get around to finishing it.

**Comment by AdrianBZG** [comment]
@ADRFranklin I have implemented proxies for Queries and Cookies (half) that are working at the moment, and distributed them across several machines. Regular sync traffic goes directly to the SAMP server.

The problem with my current cookie proxies is that they only handle the first packet (cookie request), so basically the one with 081e77da in the payload, answering with the current cookie. But to have it complete I also need to handle the reply that the client sends after that (third step), to check if it's correct according to the current cookie before letting the client get in (fourth step).

Did you manage to achieve anything with regards to these third/fourth steps?

**Comment by ADRFranklin** [comment]
You can't fix this issue at all the way you are doing it, because the server itself needs to generate a cookie for the connection itself which it stores internally to validate the connection. If you are doing this yourself then the server will always drop any client packets you proxy to it. The server has to be able to validate the connection before it will continue processing it. 

Also I also find that this route will not work out for you, because you might be able to check for them sending invalid responses, but what happens if they decide to keep sending valid responses? There would be no way to work out if the person sending it is an attacker or a legit user. 

At the end of the day the server has to be the one in control of this process. The only way I could see this working, is if you wrote a plugin that hooks into sa-mp and removes the connection cookie check all together, and then you re-implement such a thing on your end. But that is something that would take time to do.

**Comment by AdrianBZG** [comment]
@ADRFranklin Some servers have it fixed, so I see no reason why someone else couldn't, but thanks for your feedback!

**Comment by ADRFranklin** [comment]
They don't have it fixed, they have a temp solution to a specific request. As soon as that request is modified which is a single change in the source code, your entire protection becomes useless. 

These methods require more then a little check and drop scripts.

**Comment by AdrianBZG** [comment]
@ADRFranklin Indeed, not saying this is just a matter of a little check :)

**Comment by bldd14** [comment]
@AdrianBZG Sorry for the delayed response. Usually the conncookie flood overwhelms your server so even if you cache the connection cookie like some German folk did on his proxy thing, your server will use all of your CPU and you wouldn't even be able to play it.
You can actually do some hard-coded stuff and make a LKM, which listens to your server port and check whenever it receives a connection request. If the connection gets to step 4 successfully then you let the connection actually reach the SA-MP server.
That's how SYN proxy works, you can do the same thing for RakNet connections, even.
There's not much you can do, sadly. This is a design issue and should be fixed with a client-side part.

**Comment by AdrianBZG** [comment]
@bldd14 What do you mean by LKM? Sorry I'm not familiar with the acronym.

Do you have any pointers on how one could emulate the Raknet connection cookie mechanism so that incoming connections can be redirected there and checked, removing the load from the SA-MP server?

**Comment by bldd14** [comment]
@AdrianBZG LKM stands for Loadable Kernel Module.

Information I gave to you should be enough. iptables isn't needed in case you use LKMs, you must code it yourself.
You can look at RakSamps' code (https://github.com/6D6C666A/RakSAMP) to guide yourself.

**Comment by AdrianBZG** [comment]
@bldd14 Thanks for that, just a last bit: could you point to which file or part of the RakSAMP source does the connection handling? Thanks.

**Comment by bldd14** [comment]
@AdrianBZG 
https://github.com/LoleroChitero/RakSAMP/blob/master/raknet/RakPeer.cpp#L3986

**Comment by AdrianBZG** [comment]
@bldd14 Thanks!

**Comment by bldd14** [comment]
Remember, all packets but those which are sent by the server are encrypted!
https://github.com/LoleroChitero/RakSAMP/blob/master/raknet/RakPeer.cpp#L3986 
https://github.com/LoleroChitero/RakSAMP/blob/master/raknet/RakPeer.cpp#L3986

**Comment by AdrianBZG** [comment]
@bldd14 And you need to decrypt them using Raknet, right?

**Comment by bldd14** [comment]
If the packets are coming from the client, yes. use unkyretardizeDatagram for that and the data will be allocated on decrBuffer.

**Comment by AdrianBZG** [comment]
@bldd14 Ok, and the idea is to validate until step 4 mentioned above without letting the main SA-MP server handle that, and then when an address reaches that step successfully, how would it work to allow it to actually connect to the server? As I guess the server will need to do the connection all over again. So should that user be then whitelisted and allowed to send the packets to the actual server?

**Comment by bldd14** [comment]
Spoof the connection packet from your LKM using the player's IP.
You can disable the connection cookies in your server, that way you will only need spoof the first packet (set conncookies to 0 in your server.cfg).
NOTE: This will only reduce the harm this attack does, but will not completely fix it.

**Comment by AdrianBZG** [comment]
@bldd14 Interesting, I guess one could have such a thing on multiple instances and do some kind of load balancer to completely fix this? What do you think?

**Comment by bldd14** [comment]
Yes, it's possible indeed.

**Comment by AdrianBZG** [comment]
@bldd14 I'm unsure how the LKM would listen for only the connection packets and not the others... or would it listen for everything and forward all the sync packets by spoofing the IP to the actual server?

**Comment by bldd14** [comment]
You can place a hook before the packet reaches the iptables NAT table (in the case you're using iptables to redirect the packets), in your hook check if the IP is associated with an existing samp connection, if it isn't then the first packet should be the connection cookie or a samp query.

**Comment by AdrianBZG** [comment]
@bldd14 Have you actually implemented such kind of proxy already in the way you say?

**Comment by AdrianBZG** [comment]
@bldd14 Taking a look at the code and trying it running RakSAMP server and an actual SA-MP client, I send the ID_OPEN_CONNECTION_REQUEST, but I never send the ID_OPEN_CONNECTION_COOKIE, it seems like the cookie system is disabled in that code? Do you know how to turn it on?

**Comment by bldd14** [comment]
Yes I implemented that system some time ago.
Public RakServer conncookie system is implemented but not used so you'll need to make it work on your own.
Since your first question is answered, I'm going to close this issue, hope your doubts are cleared.

**Comment by AdrianBZG** [comment]
@bldd14 Thanks for your help, I just ended up developing a DPDK-based module.
